name: linter

on:
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
